// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/portfolio-layout/Bento.tsx": () => import("../components/mockups/portfolio-layout/Bento.tsx"),
  "./components/mockups/portfolio-layout/Sidebar.tsx": () => import("../components/mockups/portfolio-layout/Sidebar.tsx"),
  "./components/mockups/portfolio-layout/Timeline.tsx": () => import("../components/mockups/portfolio-layout/Timeline.tsx"),
  "./components/mockups/portfolio-hero/Evidence.tsx": () => import("../components/mockups/portfolio-hero/Evidence.tsx"),
  "./components/mockups/portfolio-hero/Restraint.tsx": () => import("../components/mockups/portfolio-hero/Restraint.tsx"),
  "./components/mockups/portfolio-hero/Terminal.tsx": () => import("../components/mockups/portfolio-hero/Terminal.tsx")
};
